### ISSUE TITLE
QR codes for account transfer

### ISSUE THREAD

**Issue by GeorgeMcKinlay** [TeamDentro/kristdroid#2]
Since secure accounts have long passwords, it'll be difficult to enter them on a phone. Thus, allow the app to scan QR codes containing the passwords.

**Comment by apemanzilla** [comment]
While we're at it, why not also support NFC?

**Comment by LemonLake** [comment]
That sounds pretty neat.

**Comment by LemonLake** [comment]
The code generator will be available on the teamdentro website
